services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procurepilot_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - procurepilot

    queue:
      build:
      context: .
      dockerfile: Dockerfile
      container_name: procurepilot_queue
      restart: unless-stopped
      working_dir: /var/www/html
      command: php artisan queue:work redis --queue=procurement-events,default --sleep=3 --tries=3 --timeout=90 --backoff=10
      volumes:
      - ./:/var/www/html
      depends_on:
      - app
      - db
      - redis
      networks:
      - procurepilot

  nginx:
    image: nginx:1.27-alpine
    container_name: procurepilot_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - procurepilot

  db:
    image: mysql:8.4
    container_name: procurepilot_db
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: procurepilot
      MYSQL_USER: procurepilot
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - procurepilot_mysql_data:/var/lib/mysql
    networks:
      - procurepilot

  redis:
    image: redis:7.4-alpine
    container_name: procurepilot_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - procurepilot

  mailpit:
    image: axllent/mailpit:latest
    container_name: procurepilot_mailpit
    restart: unless-stopped
    ports:
      - "8026:8025"
      - "1026:1025"
    networks:
      - procurepilot

  ai-service:
    build:
      context: ./fastapi-service
      dockerfile: Dockerfile
    container_name: procurepilot_ai_service
    restart: unless-stopped
    ports:
      - "8001:8000"
    networks:
      - procurepilot

networks:
  procurepilot:
    driver: bridge

volumes:
  procurepilot_mysql_data:
    driver: local
